from base.data_validation_fucn import *

invalid_cases = [
    ("Empty string (income, visible)", {"name": "", "is_income": True, "is_outcome": False, "is_visibility": True}),
    ("Empty string (income, invisible)", {"name": "", "is_income": True, "is_outcome": False, "is_visibility": False}),
    ("Empty string (outcome, visible)", {"name": "", "is_income": False, "is_outcome": True, "is_visibility": True}),
    ("Empty string (outcome, invisible)", {"name": "", "is_income": False, "is_outcome": True, "is_visibility": False}),
    ("Only space (outcome, visible)", {"name": " ", "is_income": False, "is_outcome": True, "is_visibility": True}),
    ("Only space (outcome, invisible)", {"name": " ", "is_income": False, "is_outcome": True, "is_visibility": False}),
    ("Only space (income, visible)", {"name": " ", "is_income": True, "is_outcome": False, "is_visibility": True}),
    ("Only space (income, invisible)", {"name": " ", "is_income": True, "is_outcome": False, "is_visibility": False}),
    ("Length > 14 (income, visible)", {"name": fake.text(max_nb_chars=15), "is_income": True, "is_outcome": False, "is_visibility": True}),
    ("Length > 14 (income, invisible)", {"name": fake.text(max_nb_chars=15), "is_income": True, "is_outcome": False, "is_visibility": False}),
    ("Length > 14 (outcome, visible)", {"name": fake.text(max_nb_chars=15), "is_income": False, "is_outcome": True, "is_visibility": True}),
    ("Length > 14 (outcome, invisible)", {"name": fake.text(max_nb_chars=15), "is_income": False, "is_outcome": True, "is_visibility": False}),
    ("Forbidden characters (outcome, visible)", {"name": generate_invalid_string(length=10), "is_income": False, "is_outcome": True, "is_visibility": True}),
    ("Forbidden characters (outcome, invisible)", {"name": generate_invalid_string(length=10), "is_income": False, "is_outcome": True, "is_visibility": False}),
    ("Forbidden characters (income, visible)", {"name": generate_invalid_string(length=10), "is_income": True, "is_outcome": False, "is_visibility": True}),
    ("Forbidden characters (income, invisible)", {"name": generate_invalid_string(length=10), "is_income": True, "is_outcome": False, "is_visibility": False}),
    ("Forbidden symbol '_' (income, visible)", {"name": generate_invalid_category_with_underscore(), "is_income": True, "is_outcome": False, "is_visibility": True}),
    ("Forbidden characters + text (outcome, visible)", {"name": generate_invalid_string(with_text=True, text_length=5), "is_income": False, "is_outcome": True, "is_visibility": True}),
    ("Forbidden characters + text (outcome, invisible)", {"name": generate_invalid_string(with_text=True, text_length=5), "is_income": False, "is_outcome": True, "is_visibility": False}),
    ("Forbidden characters + text (income, visible)", {"name": generate_invalid_string(with_text=True, text_length=5), "is_income": True, "is_outcome": False, "is_visibility": True}),
    ("Forbidden characters + text (income, invisible)", {"name": generate_invalid_string(with_text=True, text_length=5), "is_income": True, "is_outcome": False, "is_visibility": False}),
    ("Forbidden symbol '_' (income, invisible)", {"name": generate_invalid_category_with_underscore(), "is_income": True, "is_outcome": False, "is_visibility": False}),
    ("Forbidden symbol '_' (outcome, visible)", {"name": generate_invalid_category_with_underscore(), "is_income": False, "is_outcome": True, "is_visibility": True}),
    ("Forbidden symbol '_' (outcome, invisible)", {"name": generate_invalid_category_with_underscore(), "is_income": False, "is_outcome": True, "is_visibility": False}),
    ("Number > 14 characters (outcome, visible)", {"name": generate_random_string(), "is_income": False, "is_outcome": True, "is_visibility": True}),
    ("Number > 14 characters (outcome, invisible)", {"name": generate_random_string(), "is_income": False, "is_outcome": True, "is_visibility": False}),
    ("Number > 14 characters (income, visible)", {"name": generate_random_string(), "is_income": True, "is_outcome": False, "is_visibility": True}),
    ("Number > 14 characters (income, invisible)", {"name": generate_random_string(), "is_income": True, "is_outcome": False, "is_visibility": False}),
    ("Outcome = Income = False (visible)", {"name": generate_valid_category(), "is_income": False, "is_outcome": False, "is_visibility": True}),
    ("Outcome = Income = False (invisible)", {"name": generate_valid_category(), "is_income": False, "is_outcome": False, "is_visibility": False}),
    ("Outcome = Income = True (visible)", {"name": generate_valid_category(), "is_income": True, "is_outcome": True, "is_visibility": True}),
    ("Outcome = Income = True (invisible)", {"name": generate_valid_category(), "is_income": True, "is_outcome": True, "is_visibility": False}),
]

valid_data = [
    ("Valid category (outcome, invisible) with uppercase Russian letters (random choice)",
     {"name": generate_random_russian_uppercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with uppercase English letters (random choice)",
     {"name": generate_random_english_uppercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with uppercase Russian and English letters (random choice)",
     {"name": generate_random_english_russian_uppercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with lowercase Russian letters (random choice)",
     {"name": generate_random_russian_lowercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with lowercase English letters (random choice)",
     {"name": generate_random_english_lowercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with lowercase Russian and English letters (random choice)",
     {"name": generate_random_english_russian_lowercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with uppercase and lowercase letters (English, random choice)",
     {"name": generate_random_english_mixed_case_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with uppercase and lowercase letters (Russian, random choice)",
     {"name": generate_random_russian_mixed_case_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (income, visible) with uppercase Russian letters (random choice)",
     {"name": generate_random_russian_uppercase_category(), "is_income": True, "is_outcome": False,
      "is_visibility": True}),
    ("Valid category (income, visible) with uppercase English letters (random choice)",
     {"name": generate_random_english_uppercase_category(), "is_income": True, "is_outcome": False,
      "is_visibility": True}),
    ("Valid category (income, visible) with uppercase Russian and English letters (random choice)",
     {"name": generate_random_english_russian_uppercase_category(), "is_income": True, "is_outcome": False,
      "is_visibility": True}),
    ("Valid category (income, visible) with lowercase Russian letters (random choice)",
     {"name": generate_random_russian_lowercase_category(), "is_income": True, "is_outcome": False,
      "is_visibility": True}),
    ("Valid category (income, visible) with lowercase English letters (random choice)",
      {"name": generate_random_english_lowercase_category(), "is_income": True, "is_outcome": False,
       "is_visibility": True}),
    ("Valid category (income, visible) with lowercase Russian and English letters (random choice)",
     {"name": generate_random_english_russian_lowercase_category(), "is_income": True, "is_outcome": False,
      "is_visibility": True}),
    ("Valid category (income, visible) with uppercase and lowercase letters (English, random choice)",
     {"name": generate_random_english_mixed_case_category(), "is_income": True, "is_outcome": False,
      "is_visibility": True}),
    ("Valid category (income, visible) with uppercase and lowercase letters (Russian, random choice)",
     {"name": generate_random_russian_mixed_case_category(), "is_income": True, "is_outcome": False,
      "is_visibility": True}),
    ("Valid category (outcome, invisible) with uppercase Russian letters (random choice)",
     {"name": generate_random_russian_uppercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with uppercase English letters (random choice)",
     {"name": generate_random_english_uppercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with uppercase Russian and English letters (random choice)",
     {"name": generate_random_english_russian_uppercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with lowercase Russian letters (random choice)",
     {"name": generate_random_russian_lowercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
    ("Valid category (outcome, invisible) with lowercase English letters (random choice)",
     {"name": generate_random_english_lowercase_category(), "is_income": False, "is_outcome": True,
      "is_visibility": False}),
]
